#!/bin/bash
#SBATCH -J mpi0 
# time 2 day and 23 hour, in parallel partition, you can only run one day max, and the number of jobs has to be dozens
#SBATCH -o mpi.out
#SBATCH -e mpi.err
#SBATCH -n 5 
#SBATCH -p parallel 
#SBATCH --time=2-23:59:0
#SBATCH --mem-per-cpu=1000

# module swap intel/13.1.0 gcc/4.8.2
module load intelmpi/4.1.0 
module load python-env/2.7.3
# module load python/2.7.3 
# cd ~/tools
srun ./getSlides_mpi.py 
